RCT-101: React Basics/Components, Props, and States
rchie01/dotTheory-React pull request #1
Opened 2022-10-04 03:44 UTC by rchie01

# Related Tickets

https://codeandtheory.atlassian.net/browse/RCT-129

# Description

- Creates a scoreboard using Components, Props, States, and Events in React

# Validation

- Clone the repository using SSH or HTTPS
- Open the RCT-101 folder
- Go Live using the **Live Server** extension in VSCode
- Interact with the scoreboard by removing players (hover over on the left side of the player's name), and adding and deducting player points by using the buttons.

The scoreboard, along with its basic features as guided by the training module should be observed. 

# Risks
- N/A

2023-04-05 09:07 UTC, lycoangelo requested changes

2023-04-05 09:07 UTC, lycoangelo commented on RCT-101/app.css
> +  }
Indentation here is not consistent with the others. Also, no new line at EOF.

2023-04-05 09:07 UTC, lycoangelo commented on RCT-101/app.js
> +    console.log(props);
Stray log.

2023-04-05 09:07 UTC, lycoangelo commented on RCT-101/app.js
Please convert tabs to two spaces.

2023-04-05 09:07 UTC, lycoangelo commented on RCT-101/app.js
> +    render(){
Missing space after the parenthesis.

2023-04-05 09:07 UTC, lycoangelo commented on RCT-101/app.js
> +                <button className="counter-action increment" onClick = {() => this.appPoint()}>+</button>
`onClick={this.deductPoint}` should simplify the event callback assignment here.

2023-04-05 09:07 UTC, lycoangelo commented on RCT-101/app.js
> +    constructor(){
Missing space after the parenthesis.

2023-04-05 09:07 UTC, lycoangelo commented on RCT-101/app.js
> +    render(){
Missing space after the parenthesis.

2023-04-05 09:07 UTC, lycoangelo commented on RCT-101/app.js
> +                    return(
Missing space after the `return` keyword.

2023-04-05 09:07 UTC, lycoangelo commented on RCT-101/app.js
> +                        />
Please fix indentations and unnecessary empty lines.

2023-04-05 09:07 UTC, lycoangelo commented on RCT-101/app.js
> +};
Could be an implicit return.

2023-05-25 07:32 UTC, rchie01 commented
The aforementioned changes requested above were addressed in the most recent commit. @lycoangelo

2023-10-06 18:56 UTC, closed without merging