RCT-102: Using Create React App
rchie01/dotTheory-React pull request #2
Opened 2022-11-10 07:16 UTC by rchie01

# Related Tickets

https://codeandtheory.atlassian.net/browse/RCT-130

# Description

- Creates a simple React Application using `create-react-app`
- This PR intends to demonstrate the use of `create-react-app`

# Validation

- Clone the repository using SSH or HTTPS
- Open the search-app folder located in the RCT-102 folder.
- Run `npm start`

The user should be able to see components imported from `react-bootstrap`.

# Risks
- N/A

2023-04-05 09:19 UTC, lycoangelo requested changes

2023-04-05 09:19 UTC, lycoangelo commented on RCT-102/search-app/src/components/SearchForm.js
> +
Please be consistent with the indentation. Let's just use two spaces.

2023-04-05 09:19 UTC, lycoangelo commented on RCT-102/search-app/src/components/Results.js
Let's just use two spaces for indentations.

2023-04-05 09:19 UTC, lycoangelo commented on RCT-102/search-app/src/App.js
> +    <div >
There's an unnecessary space.

2023-04-05 09:19 UTC, lycoangelo commented on RCT-102/search-app/src/App.js
> +    </div>
Please fix the indentations.

2023-05-25 07:49 UTC, rchie01 commented
The aforementioned changes requested above were addressed in the most recent commit. @lycoangelo

2023-10-06 18:55 UTC, closed without merging