RCT-103: React Components
rchie01/dotTheory-React pull request #3
Opened 2022-11-10 07:33 UTC by rchie01

# Related Tickets

https://codeandtheory.atlassian.net/browse/RCT-131

# Description

- Creates a simple Scoreboard application using `create-react-app`
- This PR demonstrates the use of building modular interfaces with components, management of state and data flow, lifecycle methods and stateful components, and React Component patterns

# Validation

- Clone the repository using SSH or HTTPS
- The video course challenge is separated into two coding challenges

Part 1:
1. Open the RCT-103 folder and open the _**../create-react-app-demo/scoreboard**_ folder
2. Run `npm start` (tested using _**node v18.0.0**_)
3. Interact with the application by starting/stopping and resetting the timer, remove current players, add new players, and increase and decrease the scores

Part 2:
1. Open the RCT-103 folder and open the _**../scoreboard**_ folder
2. Go Live using the **Live Server** extension in VSCode
5. Interact with the application by increasing and/or decreasing the scores of one of the players

The user should be able to interact with the applications as intended

# Risks
- N/A

2023-04-05 09:30 UTC, lycoangelo requested changes

2023-04-05 09:30 UTC, lycoangelo commented on RCT-103/create-react-app-demo/scoreboard/src/components/AddPlayerForm.js
> +    let input = useRef();
Use `const` instead of `let` if the variable value is not reassigned.

2023-04-05 09:30 UTC, lycoangelo commented on RCT-103/create-react-app-demo/scoreboard/src/components/AddPlayerForm.js
> +        <form onSubmit={(e)=>{handleSubmit(e)}}>
`onSubmit={handleSubmit}` should simplify this and have the same result.

2023-04-05 09:30 UTC, lycoangelo commented on RCT-103/create-react-app-demo/scoreboard/src/components/AddPlayerForm.js
Please convert tabs to two spaces.

2023-04-05 09:30 UTC, lycoangelo commented on RCT-103/create-react-app-demo/scoreboard/src/components/App.js
> +  const [highScore, setHighScore] = useState();
A default value here would be helpful.

2023-04-05 09:30 UTC, lycoangelo commented on RCT-103/create-react-app-demo/scoreboard/src/components/App.js
> +      if(player.id === id){
Missing space after the closing parenthesis.

2023-04-05 09:30 UTC, lycoangelo commented on RCT-103/create-react-app-demo/scoreboard/src/components/Counter.js
> +  export default Counter;
Indentations are off.

2023-04-05 09:30 UTC, lycoangelo commented on RCT-103/create-react-app-demo/scoreboard/src/components/Header.js
Please convert tabs to two spaces.

2023-04-05 09:30 UTC, lycoangelo commented on RCT-103/create-react-app-demo/scoreboard/src/components/Icon.js
Please convert tabs to two spaces.

2023-04-05 09:30 UTC, lycoangelo commented on RCT-103/create-react-app-demo/scoreboard/src/components/Player.js
Please fix the indentation.

2023-04-05 09:30 UTC, lycoangelo commented on RCT-103/create-react-app-demo/scoreboard/src/components/Stats.js
> +        </table>
No formatted properly.

2023-04-05 09:30 UTC, lycoangelo commented on RCT-103/create-react-app-demo/scoreboard/src/components/Stats.js
Please convert tabs to two spaces.

2023-04-05 09:30 UTC, lycoangelo commented on RCT-103/create-react-app-demo/scoreboard/src/components/Stats.js
> +    const totalPoints = playerList.reduce((total, player)=>{
Please fix the spaces.

2023-04-05 09:30 UTC, lycoangelo commented on RCT-103/create-react-app-demo/scoreboard/src/components/Stats.js
> +};
Please update codes format.

2023-04-05 09:30 UTC, lycoangelo commented on RCT-103/create-react-app-demo/scoreboard/src/components/Stopwatch.js
> +        if(isRunning) {
Missing space.

2023-04-05 09:30 UTC, lycoangelo commented on RCT-103/create-react-app-demo/scoreboard/src/components/Stopwatch.js
Please convert tabs to two spaces.

2023-04-05 09:30 UTC, lycoangelo commented on RCT-103/create-react-app-demo/scoreboard/src/components/Stopwatch.js
> +    const [ isRunning, setIsRunning ] = useState(false);
Let's be consistent with spacing, indentations, etc, across all components. Let's remove the spaces here before/after the square brackets.

2023-04-05 09:30 UTC, lycoangelo commented on RCT-103/create-react-app-demo/scoreboard/src/index.css
> +}
Missing newline at EOF.

2023-05-25 09:50 UTC, rchie01 commented
The aforementioned changes requested above were addressed in the most recent commit. @lycoangelo

2023-10-06 18:55 UTC, closed without merging